#station_serial =                   # Serial number of the station

interval = 2                        # Time between measurements

toggle_intensity = 100              # The light level at which the LED should be turned on

[i2c]                               # I2C-Addresses of the sensors
#bme280 =
#bh1750 =
#mq135 =

[destination]                       # Information about the server
#ip =                               # IP-Address or Hostname of the Server
#path =                             # Path to the script that accepts the measurements
